import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import {
  apiRouteContract,
  type ApiRouteDefinition,
} from '../workers/api/src/api-route-contract';

const outputUrl = new URL('../docs/generated/API_ROUTES.md', import.meta.url);
const outputPath = fileURLToPath(outputUrl);
const checkOnly = process.argv.includes('--check');

const accessLabel = (route: ApiRouteDefinition) => {
  if (route.access === 'operator') return `operator: ${route.capability}`;
  if (route.access === 'target') return 'signed target';
  if (route.access === 'callback') return 'signed callback';
  if (route.access === 'session') return 'operator session';
  return 'public';
};

const escapeCell = (value: string) => value.replaceAll('|', '\\|');
const groups = [...new Set(apiRouteContract.map((route) => route.group))];
const sections = groups.map((group) => {
  const rows = apiRouteContract
    .filter((route) => route.group === group)
    .map(
      (route) =>
        `| ${route.method} | \`${route.path}\` | ${escapeCell(accessLabel(route))} | ${escapeCell(route.purpose)} |`,
    );
  return [
    `## ${group}`,
    '',
    '| Method | Route | Access | Purpose |',
    '| --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
});

const generated = `${[
  '# Worker API Routes',
  '',
  '> Generated from `workers/api/src/api-route-contract.ts`. Do not edit this file by hand. Run `npm run docs:generate` after changing the route contract; `npm run docs:check` rejects stale output.',
  '',
  'Path parameters are shown with a leading colon. Query parameters do not change route authorization. The two `latest` evidence routes accept `?optional=true` and return 204 when no current artifact exists.',
  '',
  'Access labels distinguish public health, operator-session verification, capability-scoped operator routes, signed target ingestion/workspaces, and execution-scoped signed repository callbacks.',
  '',
  sections.join('\n\n'),
  '',
  `**Contract total:** ${apiRouteContract.length} method/path entries.`,
].join('\n')}\n`;

if (checkOnly) {
  const current = await readFile(outputUrl, 'utf8').catch(() => '');
  if (current !== generated) {
    throw new Error(
      `${outputPath} is stale. Run npm run docs:generate and commit the result.`,
    );
  }
  process.stdout.write(
    `API route reference is current (${apiRouteContract.length} entries).\n`,
  );
} else {
  await mkdir(new URL('../docs/generated/', import.meta.url), {
    recursive: true,
  });
  await writeFile(outputUrl, generated, 'utf8');
  process.stdout.write(
    `Generated ${outputPath} (${apiRouteContract.length} entries).\n`,
  );
}
